"""empty message

Revision ID: 10fb6379208d
Revises: db8aaedf697e
Create Date: 2021-12-04 19:54:04.118906

"""

# revision identifiers, used by Alembic.
revision = '10fb6379208d'
down_revision = 'db8aaedf697e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
