"""empty message

Revision ID: 235c8cec84ab
Revises: 24a4f34ddd7c
Create Date: 2021-12-04 19:37:44.771595

"""

# revision identifiers, used by Alembic.
revision = '235c8cec84ab'
down_revision = '24a4f34ddd7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
