"""empty message

Revision ID: 24a4f34ddd7c
Revises: 1bded79151a5
Create Date: 2021-12-04 19:34:31.677961

"""

# revision identifiers, used by Alembic.
revision = '24a4f34ddd7c'
down_revision = '1bded79151a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
