"""empty message

Revision ID: 33b962822d3f
Revises: 98e0b2fd4502
Create Date: 2021-12-05 20:51:03.081212

"""

# revision identifiers, used by Alembic.
revision = '33b962822d3f'
down_revision = '98e0b2fd4502'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
