"""empty message

Revision ID: 452f1c23c3cb
Revises: 7c1716575d07
Create Date: 2021-12-05 09:33:24.048901

"""

# revision identifiers, used by Alembic.
revision = '452f1c23c3cb'
down_revision = '7c1716575d07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
