"""empty message

Revision ID: 4c9f007d4e9b
Revises: add40f1c7fae
Create Date: 2021-12-06 13:55:50.094411

"""

# revision identifiers, used by Alembic.
revision = '4c9f007d4e9b'
down_revision = 'add40f1c7fae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
