"""empty message

Revision ID: 4f9d5c54373f
Revises: e70581c0c6a5
Create Date: 2021-12-05 19:33:41.094017

"""

# revision identifiers, used by Alembic.
revision = '4f9d5c54373f'
down_revision = 'e70581c0c6a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
