"""Add color.

Revision ID: 5208c04487b1
Revises: 3264de143134
Create Date: 2022-07-15 11:27:32.130226

"""

# revision identifiers, used by Alembic.
revision = '5208c04487b1'
down_revision = '3264de143134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
