"""empty message

Revision ID: 653411527329
Revises: ce87e043e3a8
Create Date: 2021-12-05 08:57:11.139843

"""

# revision identifiers, used by Alembic.
revision = '653411527329'
down_revision = 'ce87e043e3a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
