"""empty message

Revision ID: 7c1716575d07
Revises: a64a2c9b2d05
Create Date: 2021-12-05 09:31:54.055104

"""

# revision identifiers, used by Alembic.
revision = '7c1716575d07'
down_revision = 'a64a2c9b2d05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
