"""empty message

Revision ID: 7efad773ee8c
Revises: f29297a9e664
Create Date: 2021-12-13 09:02:49.949222

"""

# revision identifiers, used by Alembic.
revision = '7efad773ee8c'
down_revision = 'f29297a9e664'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
