"""empty message

Revision ID: 93a0e6553411
Revises: 5536ff113af7
Create Date: 2021-12-04 20:58:25.621061

"""

# revision identifiers, used by Alembic.
revision = '93a0e6553411'
down_revision = '5536ff113af7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
