"""empty message

Revision ID: 962314b7ff85
Revises: 4c9f007d4e9b
Create Date: 2021-12-06 14:18:14.890411

"""

# revision identifiers, used by Alembic.
revision = '962314b7ff85'
down_revision = '4c9f007d4e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
