"""Adding column color.

Revision ID: a5aae0a04bb5
Revises: a014dc5fbd5e
Create Date: 2022-07-15 14:02:56.508756

"""

# revision identifiers, used by Alembic.
revision = 'a5aae0a04bb5'
down_revision = 'a014dc5fbd5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
