"""empty message

Revision ID: a64a2c9b2d05
Revises: 653411527329
Create Date: 2021-12-05 09:30:24.253910

"""

# revision identifiers, used by Alembic.
revision = 'a64a2c9b2d05'
down_revision = '653411527329'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
