"""empty message

Revision ID: add40f1c7fae
Revises: 6e430699b147
Create Date: 2021-12-05 22:49:59.278624

"""

# revision identifiers, used by Alembic.
revision = 'add40f1c7fae'
down_revision = '6e430699b147'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
