"""empty message

Revision ID: b1f6cab468d4
Revises: 4f9d5c54373f
Create Date: 2021-12-05 19:35:58.809120

"""

# revision identifiers, used by Alembic.
revision = 'b1f6cab468d4'
down_revision = '4f9d5c54373f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
