"""empty message

Revision ID: ca275cc4a919
Revises: 10fb6379208d
Create Date: 2021-12-04 20:17:24.337327

"""

# revision identifiers, used by Alembic.
revision = 'ca275cc4a919'
down_revision = '10fb6379208d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
