"""empty message

Revision ID: ce87e043e3a8
Revises: 93a0e6553411
Create Date: 2021-12-05 08:26:37.191497

"""

# revision identifiers, used by Alembic.
revision = 'ce87e043e3a8'
down_revision = '93a0e6553411'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
