"""empty message

Revision ID: db8aaedf697e
Revises: 235c8cec84ab
Create Date: 2021-12-04 19:41:14.397413

"""

# revision identifiers, used by Alembic.
revision = 'db8aaedf697e'
down_revision = '235c8cec84ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
