"""empty message

Revision ID: dbe28bd78c10
Revises: 7efad773ee8c
Create Date: 2021-12-13 09:32:58.952560

"""

# revision identifiers, used by Alembic.
revision = 'dbe28bd78c10'
down_revision = '7efad773ee8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
