"""empty message

Revision ID: dc0c3839e0c4
Revises: 962314b7ff85
Create Date: 2021-12-07 08:58:26.839235

"""

# revision identifiers, used by Alembic.
revision = 'dc0c3839e0c4'
down_revision = '962314b7ff85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
