"""empty message

Revision ID: e70581c0c6a5
Revises: 452f1c23c3cb
Create Date: 2021-12-05 09:34:11.666236

"""

# revision identifiers, used by Alembic.
revision = 'e70581c0c6a5'
down_revision = '452f1c23c3cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
