"""empty message

Revision ID: f29297a9e664
Revises: dc0c3839e0c4
Create Date: 2021-12-07 15:34:44.377232

"""

# revision identifiers, used by Alembic.
revision = 'f29297a9e664'
down_revision = 'dc0c3839e0c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
